CREATE TABLE IF NOT EXISTS `queue` (
  `id` CHAR(36) NOT NULL,
  `batchId` VARCHAR(32) NOT NULL DEFAULT "",
  `job` VARCHAR(200) NOT NULL DEFAULT "",
  `dueAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dispatchedAt` DATETIME NOT NULL DEFAULT NOW(),
  `lockerId` VARCHAR(32) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`batchId`, `job`),
  KEY (`lockerId`)
);

